### ISSUE TITLE
Случайные логотипы клиентов

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis.com#11]
Логотипы клиентов в списке должны меняться случайным образом

**Comment by asidarovich** [comment]
done. Логотипы 200x90px класть в каталог /clients. Выводится 6 случайных логотипов в случайном порядке.
1.5h

**Comment by simgislab** [comment]
@RuslanKiselev плиз доложи логотипов, если все работает - закрывай

**Comment by simgislab** [comment]
@asidarovich поломали страницу http://nextgis.ru/clients/

видимо папку с логотипами стоит по другому называть и вообще лучше ее положить в /img/clients

**Comment by asidarovich** [comment]
починено. переместил логотипы из /clients в /img/clients

**Comment by RuslanKiselev** [comment]
Проверено, работает.
