### ISSUE TITLE
Слишком большая разрядка заголовков в меню

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis.com#18]
Побочный эффект http://m-d.me/img/ss/20160929-120901.png

**Comment by asidarovich** [comment]
поменял padding-left с 20px на 4px

**Comment by simgislab** [comment]
@RuslanKiselev проверь плиз на айпаде, теперь должно без съезда влезать меню

**Comment by RuslanKiselev** [comment]
Ничего не изменилось. Или где проверять то?


воскресенье, 7 февраля 2016 г. пользователь Maxim Dubinin написал:

> @RuslanKiselev <https://github.com/RuslanKiselev> проверь плиз на айпаде,
> теперь должно без съезда влезать меню
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/nextgis.com/issues/18#issuecomment-181090469>.
>


-- 
С уважением,
Руслан Киселев
NextGIS, http://nextgis.ru/
+79154114241

**Comment by simgislab** [comment]
@RuslanKiselev приложи, плиз, скриншот

**Comment by RuslanKiselev** [comment]
Проверил еще раз, теперь все супер!
Скриншот в приложении.

пятница, 19 февраля 2016 г. пользователь Maxim Dubinin написал:

> @RuslanKiselev <https://github.com/RuslanKiselev> приложи, плиз, скриншот
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/nextgis.com/issues/18#issuecomment-186359626>.
>


-- 
С уважением,
Руслан Киселев
NextGIS, http://nextgis.ru/
+79154114241

**Comment by simgislab** [comment]
![img_2893](https://cloud.githubusercontent.com/assets/172806/13186637/2998014e-d758-11e5-9219-658d3bd391c1.jpg)
