### ISSUE TITLE
Проблемы с отображением пунктов в меню "Программы"

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/nextgis.com#20]
При нахождении на одной из страниц продукта (Web, Mobile, QGIS, Manager) остальные пункты подменю "Программы" становятся невидимыми, и отображаются только при наведении курсора).

Браузер - Chrome, версия 48.0.2564.103 m

![nextgis](https://cloud.githubusercontent.com/assets/6493848/12926249/89ef85ae-cf73-11e5-9c2d-1b279e5c7880.png)

**Comment by simgislab** [comment]
подтверждаю, в FF тоже самое

**Comment by asidarovich** [comment]
поправлено 
0.25
