### ISSUE TITLE
Нормализовать цвета на сайте и в иконках

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgis.com#21]
Сейчас у нас 3 или 4 синих-голубых цветов:

![image](https://cloud.githubusercontent.com/assets/1277422/12973113/7882d7fa-d0bb-11e5-8a4e-bbf2efc588a3.png)

Это смотреться не очень хорошо.

**Comment by lisovenkoNastya** [comment]
в связи со сменой дизайна, на мой взгляд, проблема исчезла
