### ISSUE TITLE
Нет ссылки на apk логгера

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis.com#22]
На странице http://nextgis.ru/nextgis-logger/ нет ссылки на apk.

**Comment by simgislab** [comment]
@4eRTuk сделай плиз страницу с релизом, чтобы я сослался на APK как здесь:  http://nextgis.ru/nextgis-mobile/ (см. ссылку на апк)

**Comment by 4eRTuk** [comment]
https://github.com/nextgis/nextgislogger/releases/tag/v1.5.2
