### ISSUE TITLE
добавить картинки на страницы NGL и NGF

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis.com#24]
Logger
Formbuilder

по аналогии с NGW, NGQ

не забыть про английский

**Comment by RuslanKiselev** [comment]
Сделано

**Comment by simgislab** [comment]
@MikhanGusev А можно тут же в нижний правый угол добавить картинку с мобильным с той же формой?

**Comment by simgislab** [comment]
сделано: http://nextgis.ru/en/nextgis-formbuilder/
