### ISSUE TITLE
Закругление уголков в выделении в меню

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis.com#27]
Очень желательно, что бы оно было одинаковым везде. Скругление есть, значит должно быть всегда.

![](http://m-d.me/img/ss/20160222-ga6-10kb.jpg)

Тоже самое касается и раскрытых блоков (хотя возможно это про одно и тоже)

![](http://m-d.me/img/ss/20160222-jnl-13kb.jpg)

**Comment by lisovenkoNastya** [comment]
В меню еще есть "важный пункт" (сейчас это "Стажировка"), он сейчас без закругленных уголков.
Если все делать с одинаковым скруглением (что верно), то получим ситуацию, когда текущий и "важный" пункты выглядят одинаково
![image](https://cloud.githubusercontent.com/assets/16019740/14745457/0d081018-08b4-11e6-8ba5-f58dcfd500bf.png)

Надо придумать, как по-другому выделять важный пункт.
Варианты от меня:
1)
![image](https://cloud.githubusercontent.com/assets/16019740/14745517/56e29550-08b4-11e6-867b-b0189c3aaa64.png)

2)
![image](https://cloud.githubusercontent.com/assets/16019740/14745559/8b325e6c-08b4-11e6-99cc-b2b3e69b6f6a.png)

3)
![image](https://cloud.githubusercontent.com/assets/16019740/14745598/b794f1ea-08b4-11e6-84c4-cfce111314f9.png)

**Comment by simgislab** [comment]
мне нравится 2!

**Comment by asidarovich** [comment]
Поправил всё на закругленное. Установил спецпункту меню голубой цвет (как на скриншоте номер 2) . Осталось разобраться с цветом спецпункта, когда он активен.
1h

**Comment by lisovenkoNastya** [comment]
уголков больше нет. закрываю
