### ISSUE TITLE
Слово "Пароль" налезает на точки.

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis.com#33]
Слово "Пароль" налезает на точки.
![2016-05-20 15 44 29](https://cloud.githubusercontent.com/assets/4630662/15428050/df300656-1ea1-11e6-97a9-cc025366b716.png)

По нажатию клавиши PrintScreen слово сьъезжает с точек наверх.
Ununtu

**Comment by simgislab** [comment]
непонятно что это такое вообще
