### ISSUE TITLE
После вспоминания пароля, при заходе в аккаунт уведомления налезают на текст

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis.com#34]
![2016-05-23 12 20 01](https://cloud.githubusercontent.com/assets/4630662/15466138/c15234ce-20e0-11e6-927f-1c082f53311c.png)

**Comment by trolleway** [comment]
Сбросил кеш браузера, повторяется.

**Comment by simgislab** [comment]
можно же закрыть

и видимо это вообще не очень актуально

и реп не тот, нужно в nextgisid
