### ISSUE TITLE
Нельзя добавлять фичи по WFS, созданному в Nextgis Connect

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis.com#36]
Создал слой в инстансе. Подключился к инстансу в Nextgis Connect. Создал в нём WFS, добавил в QGIS. Точки двигаются, сохраняются - всё ок. При добавлении - QGIS сообщает:
![image](https://cloud.githubusercontent.com/assets/4630662/15628704/5393d7f6-2510-11e6-9a16-74c69b8e6d7d.png)

Проверил по такому же порядку на practice2 с тем же слоем - точки создаются

**Comment by KolesovDmitry** [comment]
На стороне WFS эта ошибка выбрасывается в этом месте: https://github.com/nextgis/nextgisweb/blob/3/nextgisweb/wfsserver/nextgis_to_fs.py#L231

**Comment by simgislab** [comment]
Я повторил только что с полигональным слоем - все работает, объекты добавляются. А с точками - не работает.

**Comment by KolesovDmitry** [comment]
Эта же ошибка возникает в NGW при попытке импорта точечного слоя и создания в нем новой точки.
Похоже, там проблема связана с тем, что QGIS создает мультигеометрии, а в БД данные хранятся как простые геометрии:
```
DataError: (DataError) Geometry type (MultiPoint) does not match column type (Point)
```
Происходит это тут: https://github.com/nextgis/nextgisweb/blob/3/nextgisweb/wfsserver/nextgis_to_fs.py#L226
при попытке залить новый объект в базу: https://github.com/nextgis/nextgisweb/blob/3/nextgisweb/vector_layer/model.py#L384

@dezhin, @drnextgis, не подскажите, какая у нас политика работы с мультигеометриями?

**Comment by drnextgis** [comment]
Похоже ошибка на нашей стороне. DescribeFeatureType возвращает неправильный тип геометрии слоя, [пример](http://rykovd.nextgis.com/api/resource/5/wfs?SERVICE=WFS&REQUEST=DescribeFeatureType&typename=moscow-buildings):

```xml
<complexContent>
<extension base="gml:AbstractFeatureType">
<sequence>
<element minOccurs="0" name="is_demolition" type="string"/>
<element minOccurs="0" name="addr_full" type="string"/>
<element minOccurs="0" name="demolotion_since" type="string"/>
<element minOccurs="0" name="resettlement_from" type="string"/>
<element minOccurs="0" name="demolotion_to" type="string"/>
<element minOccurs="0" name="resettlement_to" type="string"/>
<element minOccurs="0" name="geom" type="gml:MultiPointPropertyType"/>
</sequence>
</extension>
</complexContent>
```

**Comment by KolesovDmitry** [comment]
Ошибка есть и она на нашей стороне, но вопрос немного о другом.

Какое-то время назад у нас все геометрии принудительно приводились к мультигеометриям для хранения в базе. Помнится, я даже специально менял кусок с определением типа слоя: https://github.com/nextgis/nextgisweb/commit/a5a3473178e294825cd391671b7e97688057de4e Похоже, что теперь преобразований в мультигеометрии нет.

Поэтому вопрос о политике работы с мультигеометриями не праздный и от него зависит, как править эту ошибку. Правильно ли я понял, что теперь мы храним, как мультигеометрии, так и простые? Если создается пустой слой, он будет мульти- или просто-геометрия?

**Comment by BishopGIS** [comment]
Да, в 3 ветке поддерживаются мульти и не мульти. Можешь приведение типов убирать.
А вот во 2-й все по старому.

**Comment by KolesovDmitry** [comment]
Изменил код, ошибка больше не должна появляться

**Comment by simgislab** [comment]
This issue was moved to nextgis/nextgis.com-webgis#3
