### ISSUE TITLE
Вёрстка под 1024x768 (проектор)

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis.com#37]
При подключении ноутбука к проектору (разрешение наверно 1024x768) не скроллится верхнее меню, и справа там видно только "ВО"
![screenshot from 2016-06-25 16 10 22](https://cloud.githubusercontent.com/assets/4630662/16357157/51a92f34-3af7-11e6-93f8-754a5893818b.png)
![screenshot from 2016-06-25 16 10 30](https://cloud.githubusercontent.com/assets/4630662/16357158/561e00f8-3af7-11e6-85df-5d099e0950d3.png)

**Comment by lisovenkoNastya** [comment]
http://nextgis.ru/ - исправила
за счет наличия левой панели инструментов, окно уже меньше, чем 1024
Подсобрала шапку, чтобы читалось на 940px
