### ISSUE TITLE
Ссылки при наведении курсора не меняют поведение

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis.com#6]
В меню можно поиграться с цветов на элементе, на который наведена мышь - https://yadi.sk/i/tlS8IdmdgV7N3 - каким-то бледным голубым цветом раскрасить.
В footer, например, можно сделать подчеркивание - https://yadi.sk/i/bMDAa3r8gV7eB для элемента, над которым мышь

**Comment by lisovenkoNastya** [comment]
Сейчас ссылки в меню в шапке и подвале меняют цвет при наведении
